name: Unit Test
on:
  pull_request:
jobs:
  linting:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
      
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Unit Testing
        working-directory: ./frontend
        run: npm run test
